### ISSUE TITLE
Error missing sourceBase

### ISSUE THREAD

**Issue by romariolopezc** [okwolf/fmdl#2]
```sh
fetching serverless-aws course data...
starting downloads for Serverless with AWS Lambda...
[1/32] introducing-serverless-with-aws already downloaded, skipping...
subtitles for introducing-serverless-with-aws already downloaded, skipping...
problem during course download:
  missing sourceBase for aws-lambda-functions!
```

**Comment by romariolopezc** [comment]
Same for graphql course
```sh
fetching advanced-graphql course data...
starting downloads for Advanced GraphQL...
[1/39] introducing-advanced-graphql downloaded
subtitles for introducing-advanced-graphql downloaded
problem during course download:
  missing sourceBase for graphql-api-recap!
```

**Comment by romariolopezc** [comment]
It downloads the first video and subtitles and that's it

**Comment by okwolf** [comment]
Take a look at the `course.json` file saved in one of the folders. In the `lessonData` property every object represents a lesson and there should be a `sourceBase` property on each. If they are missing then chances are something went wrong with the authentication. Maybe the session ended/cookie expired?

**Comment by romariolopezc** [comment]
Yes, some of them have the sourceBase. I'm able to download the first video only.

The patter seems the same, sourceBase + video id, I think if I do it manually is going to work but is cumbersome to modify all of them manually

**Comment by okwolf** [comment]
Manually editing the `course.json` isn't supported.

A new package has been published that should overcome several reliability issues. Please try the new version.

**Comment by romariolopezc** [comment]
Tested the new package @okwolf , still not working.

```sh
fetching advanced-graphql course data...
starting downloads for Advanced GraphQL...
subtitles for introducing-advanced-graphql downloaded
[1/39] introducing-advanced-graphql downloaded
problem during course download:
  Not Found
~
```

It downloads the first video, but then it fails

**Comment by okwolf** [comment]
Since then I've been working on a completely different strategy for this project and will be publishing an update in the near future. Stay tuned.

**Comment by romariolopezc** [comment]
Awesome! Thanks for this, if I had more time I would contribute to it

**Comment by okwolf** [comment]
I already have a prototype working, but it needs better error handling, feedback, and configuration options. Soon.

**Comment by marwicha** [comment]
i have this error too , did u fixed it?

**Comment by okwolf** [comment]
Sorry I had cancelled my subscription before finishing this, but now they are offering some free courses so that should give me a chance to test, document, and publish my rewrite.

**Comment by okwolf** [comment]
The new version is finally released! 🍾

Check out the updated readme for details.

**Comment by romariolopezc** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/6199588/44668724-c6a25d80-a9e3-11e8-8106-cb6ac05cc47d.png">

@okwolf 

I think the package.json needs update

**Comment by okwolf** [comment]
@romariolopezc I haven’t tested with yarn yet but what I intended was node 8.x not exactly 8.0. Does npm work? Perhaps I should remove the engine part of the `package.json` for now.

**Comment by okwolf** [comment]
@romariolopezc I went ahead and re-published a version without the `engines` property in `package.json`. Please try again.

**Comment by okwolf** [comment]
Don't have the time or ability to look into this any further.
